chore: Upgrade rxjs is required
Without upgrading rxjs, we get `TypeError: (0 , rxjs_1.lastValueFrom) is not a function`

This solution comes from https://github.com/nestjs/nest/issues/7468